/* Generated By:JavaCC: Do not edit this line. TableStorageParserConstants.java */
package org.apache.hadoop.zebra.types;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TableStorageParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMPRESSOR = 7;
  /** RegularExpression Id. */
  int SERIALIZER = 8;
  /** RegularExpression Id. */
  int ORDER = 9;
  /** RegularExpression Id. */
  int COMPRESS = 10;
  /** RegularExpression Id. */
  int SERIALIZE = 11;
  /** RegularExpression Id. */
  int SECURE = 12;
  /** RegularExpression Id. */
  int USER = 13;
  /** RegularExpression Id. */
  int GROUP = 14;
  /** RegularExpression Id. */
  int PERM = 15;
  /** RegularExpression Id. */
  int LETTER = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int OCTAL = 18;
  /** RegularExpression Id. */
  int SPECIALCHAR = 19;
  /** RegularExpression Id. */
  int FSSPECIALCHAR = 20;
  /** RegularExpression Id. */
  int IDENTIFIER = 21;
  /** RegularExpression Id. */
  int SHORT = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<COMPRESSOR>",
    "<SERIALIZER>",
    "\"order by\"",
    "\"compress by\"",
    "\"serialize by\"",
    "\"secure by\"",
    "\"user\"",
    "\"group\"",
    "\"perm\"",
    "<LETTER>",
    "<DIGIT>",
    "<OCTAL>",
    "<SPECIALCHAR>",
    "<FSSPECIALCHAR>",
    "<IDENTIFIER>",
    "<SHORT>",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\"#\"",
    "\".\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"|\"",
  };

}
