/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. The ASF
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package org.apache.hadoop.owl.orm;

import java.util.List;

import org.apache.hadoop.owl.common.OwlException;
import org.apache.hadoop.owl.entity.OwlEntity;
import org.apache.hadoop.owl.entity.OwlTableEntity;

/**
 * Class which extends OwlEntityManager for OwlTableEntity operations.
 */
public class OwlTableEntityManager extends OwlEntityManager<OwlTableEntity> {

    /**
     * Instantiates a new OwlTable entity manager.
     * @throws OwlException 
     */
    protected OwlTableEntityManager() throws OwlException {
        super(OwlTableEntity.class);
    }

    /**
     * Instantiates a new OwlTable entity manager.
     * 
     * @param owlEntityManager
     *            the owl entity manager
     */
    protected OwlTableEntityManager(OwlEntityManager<? extends OwlEntity> owlEntityManager) {
        super(OwlTableEntity.class, owlEntityManager);
    }


    /* (non-Javadoc)
     * @see org.apache.hadoop.owl.orm.OwlEntityManager#fetchByFilter(java.lang.String)
     */
    @Override
    public List<OwlTableEntity> fetchByFilter(String filter) throws OwlException {
        //Call the key query builder to handle filters with key conditions
        KeyQueryBuilder queryBuilder = new KeyQueryBuilder(this, "OwlTableEntity");
        String[] query = queryBuilder.buildQuery(filter, "owlTable");

        //Run the query generated by the query builder
        List<OwlTableEntity> owlTables = fetchByFilter(query[0], query[1]);
        return owlTables;
    }

}