in = LOAD '$INFILE' USING AvroStorage('','');
step1 = FOREACH in GENERATE TOTUPLE(key) as A, TOTUPLE(intValue) as C;
step2 = FOREACH step1 GENERATE A, TOTUPLE(C) as B;
step3 = FOREACH step2 GENERATE FLATTEN(A), FLATTEN(B);
out = FOREACH step3 GENERATE A::key, FLATTEN(B::C);
RMF $OUTFILE;
STORE out INTO '$OUTFILE' USING AvroStorage('$AVROSTORAGE_OUT_1','$AVROSTORAGE_OUT_2');