FROM vladistan/gradle:plus_ant

RUN useradd --no-log-init --home-dir /app --uid 200 user < /dev/null
RUN useradd --no-log-init --home-dir /app --uid 498 go < /dev/null
RUN useradd --no-log-init --home-dir /app --uid 1000 ec2-user < /dev/null
RUN useradd --no-log-init --home-dir /app --uid 1001 go2 < /dev/null
RUN useradd --no-log-init --home-dir /app --uid 500345588 me-user < /dev/null

