in = LOAD '$INFILE' USING AvroStorage('', '$AVROSTORAGE_IN_2');
out = FOREACH in GENERATE $0, $1;
RMF $OUTFILE;
STORE out INTO '$OUTFILE' USING AvroStorage('$AVROSTORAGE_OUT_1', '$AVROSTORAGE_OUT_2');